appName: FileWatcher
appPath: /mnt/c/Users/u161355/Documents/FileWatcher/filewatcher
args:
  default:
    minsize: 1B
    regex: ''
    timewait: 00:00:00
    worker: 10
data:
  path: /mnt/c/Users/u161355/Documents/FileWatcher/filewatcher/data
logs:
  defaultFile: filewatcher_deamon.log
  logFormat: '%Y-%m-%d %H:%M:%S'
  logLevel: INFO
  logMessage: '%(asctime)s [%(levelname)s] [%(threadName)s | %(funcName)s]  %(message)s'
  path: /mnt/c/Users/u161355/Documents/FileWatcher/filewatcher/logs
pid:
  defaultFile: deamonrun.pid
  path: /mnt/c/Users/u161355/Documents/FileWatcher/filewatcher/pid
